controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

import:
    path: /import
    controller: App\Controller\AppController::import